stages:
  - build
  - publish

variables:
  BUILD_FOLDER: target/release/my-service-bus
  DOCKER_IMAGE_TAG: amigin/my-service-bus


test-and-build:
  stage: build
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo test
    - cargo build --release
  artifacts:
    paths:
      - ${BUILD_FOLDER}

publish:
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - ver=$(cat Cargo.toml | grep -m1 version | grep  -Eo '["\047].*["\047]' | tr -d '"')
    - echo $ver
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
    - docker build -t ${DOCKER_IMAGE_TAG}:$ver .
    - docker push ${DOCKER_IMAGE_TAG}:$ver
  image: docker:latest
