[package]
name = "my-service-bus"
version = "2.0.7"
authors = ["amigin <amigin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-azure-storage-sdk = { branch = "main", git = "https://github.com/MyJetTools/my-azure-storage.git" }
my-azure-page-blob = { branch = "main", git = "https://github.com/MyJetTools/my-azure-page-blob.git" }
my-service-bus-shared = { branch = "main", git = "https://github.com/MyJetTools/my-service-bus-shared.git" }
my-service-bus-tcp-shared = { branch = "main", git = "https://github.com/MyJetTools/my-service-bus-tcp-shared.git" }
rust-extensions = { branch = "main", git = "https://github.com/MyJetTools/rust-extensions.git" }

tonic = { version = "0.5.0", features = ["tls", "tls-roots", "prost"] }

hyper = { version = "0.14.7", features = ["full"] }
tokio = { version = "*", features = ["full"] }
tokio-util = "*"
chrono = "*"
lazy_static = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
serde_yaml = "*"
base64 = "*"
zip = "*"
md5 = "*"
anyhow = "1.0.40"
futures-core = "*"
prost = "0.8.0"
prost-types = "0.8.0"
tokio-stream = "*"
async-trait = "*"
futures-util = "*"
tokio-signal = "*"
signal-hook = "*"
rand = "*"
sysinfo = "*"
prometheus = "0.13.0"
uuid = { version = "*", features = ["serde", "v4"] }


[build-dependencies]
tonic-build = { version = "0.5.0", features = ["prost"] }
